# Site settings
author: Alisa Cookie McCormick
title: Alisa Cookie McCormick
header-img: img/home-bg.png
email: alisa.cookie.mccormick@gmail.com
copyright_name: Alisa Cookie McCormick
description: > # this means to ignore newlines until "baseurl:"
  Becoming a Full Stack Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cookiemccormick

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
